server:
#  servlet-path: /pipe   # custom servlet-path
  port: 8080            # default server port, if not set otherwise

# Math AST Renderer - Main URL
mast.url: http://math.citeplag.org

# the use of the latexml online service (via url) is optional
# if service is not found or configured properly fallback is the local latexml installation
latexml:
  active: true
  url: https://drmf-latexml.wmflabs.org # set a url if you want the option of the online service
  params:                             # parameters for the online service
    whatsin: math
    whatsout: math
    includestyles:
    format: xhtml
    pmml:
    cmml:
    nodefaultresources:
    linelength: 90
    mathtex:
    quiet:
    preload:
      - "LaTeX.pool"
      - "article.cls"
      - "amsmath.sty"
      - "amsthm.sty"
      - "amstext.sty"
      - "amssymb.sty"
      - "eucal.sty"
      - "DLMFmath.sty"
      - "[dvipsnames]xcolor.sty"
      - "url.sty"
      - "hyperref.sty"
      - "[ids]latexml.sty"
      - "texvc"
      - "wikidata.sty"
      - "mleftright.sty"
    stylesheet: "DRMF.xsl"

# Mathoid - alternative Latex to MathML converter
mathoid:
  active: true
  url: http://localhost:10044/mml

translator:
  jarPath: "/home/andreg-p/Projects/latex-grammar/latex-to-cas-translator.jar"
  referencesPath: "/home/andreg-p/Projects/latex-grammar/libs/ReferenceData"
