lacast.libs.path: ./LaCASt/libs
lacast.config.path: ./LaCASt/config

lacast.cas:
  Maple:
  Mathematica:
    install.path: "/opt/Wolfram"
  SymPy:

lacast.generic:
  elasticsearch.host: "172.17.0.1"
  elasticsearch.port: 9200
  elasticsearch.macros.index: "dlmf-macros"
  mathoid.url: "http://172.17.0.1:10044/texvcinfo"