lacast.libs.path: ./LaCASt/libs
lacast.config.path: ./LaCASt/config

lacast.cas:
  - cas: "Maple"
    paths:
      - "/opt/maple2019"
      - "/opt/maple2019/bin.X86_64_LINUX"
  - cas: "Mathematica"
    paths: "/opt/Wolfram"
  - cas: "SymPy"

lacast.generic:
  elasticsearch.host: "localhost"
  elasticsearch.port: 9200
  elasticsearch.macros.index: "dlmf-macros"
  mathoid.url: "http://localhost:10044/texvcinfo"